K22CNTT4_2210900141_NGUYENMINHPHUONG_APS.NET-MVC/Lesson9+10/NmpLesson10/NmpLesson10/Controllers/NmpHomeController.cs
using NmpLesson10.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NmpLesson10.Controllers
{
    public class NmpHomeController : Controller
    {
        public ActionResult NmpIndex()
           
        {
            //Kiểm tra dữ liệu trong session
            if (Session["NmpAccounts"]!=null)
            {
                var nmpAccount = Session["NmpAcounts"] as NmpAccount;
                ViewBag.FullName = nmpAccount.NmpFullName;
            }    
            return View();
        }

        public ActionResult NmpAbout()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult NmpContact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

K22CNTT4_2210900141_NGUYENMINHPHUONG_APS.NET-MVC/Lesson9+10/NmpLesson10/NmpLesson10/Views/Shared/_NmpLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Nguyễn Minh Phương</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Nguyễn Minh Phương ", "NmpIndex", "NmpHome", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "NmpIndex", "NmpHome", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "NmpAbout", "NmpHome", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "NmpContact", "NmpHome", new { area = "" }, new { @class = "nav-link" })</li>

                    <li>@Html.ActionLink("Đăng nhập ", "NmpLogin", "NmpAccounts", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Đăng ký ", "NmpRegsty", "NmpAccount", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Nguyễn Minh Phương </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>